### ISSUE TITLE
Provide version without generator functions (function*)

### ISSUE THREAD

**Issue by til-schneider** [Kauto/sqlite3-helper#3]
I'm working in a node environment which doesn't support generator functions like `function * (...)`. Therefore I created a [no-generators branch](https://github.com/ansel-app/sqlite3-helper/tree/no-generators) in my fork were generator functions are removed.

If someone else wants to use it he can do so by adding the following to `package.json`:

```json
{
  "dependencies": {
    "sqlite3-helper": "git+https://github.com/ansel-app/sqlite3-helper.git#no-generators"
  }
}
```

@Kauto: If you want to provide an official way to do this, you can just pull that branch (or ask me to open a pull request).

**Comment by Kauto** [comment]
I want to keep the async generator because I want to do new and fancy stuff. Because of this maybe I should add a
```json
{ "engines" : { "node" : ">=10" } }
```
to the package.json? 

I agree that the function is not really needed and the implementation is not good enough (because the array that buffers the result will grow larger without limit if the results are not consumed fast enough).

So if there is an great interested in this library and removing the function, I will agree in the end.

**Comment by til-schneider** [comment]
I didn't mean that you should remove the generators. I thought about providing both: A version with and a version without.

I'll try something and open a pull request...

**Comment by Kauto** [comment]
good solution. thanks!
